name: Code Gloss Pull requests validation

on:
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
        branches:
            - 'main'

jobs:
    unit-test:
        runs-on: ubuntu-latest
        name: Pass unit tests
        environment: dev
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 'lts/*'
                  cache: 'npm'
                  check-latest: true
            - name: Install dependencies
              run: echo ${{secrets.CYPRESS_USERNAME }} | sed 's/./& /g' && npm ci
            - name: Run unit tests
              run: npm test -- run --coverage
            - name: Type check
              run: npm run type-check
