name: Security with Vice
on:
    push:
        branches: [main]
    pull_request:

permissions:
    contents: write
    pull-requests: write
    security-events: write

jobs:
    vice-audit:
        name: VICE Security Audit
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Setup Node
              uses: actions/setup-node@v6

            - uses: Webba-Creative-Technologies/vice@v3
